base: ghcr.io/vanilla-os/core:main
name: Vanilla Desktop
id: vanilla-desktop
labels:
  maintainer: Vanilla OS Contributors
args:
  DEBIAN_FRONTEND: noninteractive
runs:
- echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends
- apt install -y meson build-essential libadwaita-1-dev gettext

modules:
- name: init-setup
  type: shell
  commands:
  - echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"' > /etc/environment
  - sed -i '4,10d' /etc/profile
  - apt update
  - apt upgrade -y
  - apt clean

- name: vanilla-tools
  type: shell
  source:
    type: tar
    # switch to production build once in production
    url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/continuous/vanilla-tools.tar.gz
  commands:
  - mkdir -p /usr/bin
  - cp /sources/vanilla-tools/lpkg /usr/bin/lpkg
  - chmod +x /usr/bin/lpkg

- name: apx-gui
  type: meson
  source:
    type: git
    url: https://github.com/Vanilla-OS/apx-gui
    branch: main
    tag: v0.1

- name: packages-modules
  type: includes
  includes:
    - modules/00-vanilla-backgrounds.yml
    - modules/00-vanilla-first-setup.yml
    - modules/00-vanilla-gnome-default-settings.yml
    - modules/00-vanilla-system-operator.yml
    - modules/01-vanilla-cleanup.yml
    - modules/20-gnome-core.yml
    - modules/30-gnome-essentials.yml
    - modules/40-gnome-appearance.yml
    - modules/50-laptop-goodies.yml
    - modules/60-media.yml
    - modules/80-printers.yml
    - modules/90-3d-utils.yml
    - modules/100-accessibility.yml
    - modules/110-fonts.yml
    - modules/120-network.yml
    - modules/130-plymouth.yml
    - modules/140-password.yml
    - modules/160-utilities.yml
    - modules/200-gnome-common.yml
    - modules/210-libs-extra.yml

- name: cleanup
  type: shell
  commands:
  - apt remove -y meson build-essential libadwaita-1-dev gettext
  - apt autoremove -y
  - apt clean
  - chmod +x /usr/bin/pkg-lock && chmod +x /usr/bin/pkg-unlock
  - pkg-lock

